# An example of ClusterConfig object with highly available NAT gateways
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-otg
  region: us-west-2
  
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

vpc:
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

managedNodeGroups:
  - name: ng-12345
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: ec2-us-west-2
