# An example of ClusterConfig object with highly available NAT gateways
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-otg
  region: us-west-2
  
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

vpc:
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

managedNodeGroups:
  - name: ng-12345
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    availabilityZones: ["us-west-2a", "us-west-2b"]
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: ec2-us-west-2
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
