# An example of ClusterConfig object with highly available NAT gateways
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-9
  region: eu-west-1
  
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

vpc:
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

managedNodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 8
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    availabilityZones: ["eu-west-1a"]
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key
